"""interviews and question bank

Revision ID: c69da179b5c1
Revises: 160aab7b10be
Create Date: 2026-10-09 08:36:07.230216
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c69da179b5c1"
down_revision: str | None = "160aab7b10be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interviews",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=True),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("round_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("round_type", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("interviewers", sa.String(length=500), nullable=True),
        sa.Column("interviewer_contact_id", sa.BigInteger(), nullable=True),
        sa.Column("meeting_link", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="SCHEDULED", nullable=False),
        sa.Column(
            "topics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("result", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("next_round", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_interviews_application_id_applications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_interviews_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interviewer_contact_id"],
            ["contacts.id"],
            name=op.f("fk_interviews_interviewer_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_interviews_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
    )
    op.create_index(
        op.f("ix_interviews_application_id"), "interviews", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_interviews_company_id"), "interviews", ["company_id"], unique=False)
    op.create_index(op.f("ix_interviews_job_id"), "interviews", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_interviews_scheduled_at"), "interviews", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_interviews_status"), "interviews", ["status"], unique=False)
    op.create_table(
        "interview_questions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("technology", sa.String(length=80), nullable=True),
        sa.Column("difficulty", sa.String(length=10), nullable=True),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("job_id", sa.BigInteger(), nullable=True),
        sa.Column("interview_id", sa.BigInteger(), nullable=True),
        sa.Column("round_type", sa.String(length=30), nullable=True),
        sa.Column("expected_answer", sa.Text(), nullable=True),
        sa.Column("my_answer", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("times_practiced", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_interview_questions_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_interview_questions_interview_id_interviews"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_interview_questions_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_questions")),
    )
    op.create_index(
        op.f("ix_interview_questions_category"), "interview_questions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_interview_questions_company_id"),
        "interview_questions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_interview_questions_confidence", "interview_questions", ["confidence"], unique=False
    )
    op.create_index(
        op.f("ix_interview_questions_interview_id"),
        "interview_questions",
        ["interview_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_questions_technology"),
        "interview_questions",
        ["technology"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_questions_technology"), table_name="interview_questions")
    op.drop_index(op.f("ix_interview_questions_interview_id"), table_name="interview_questions")
    op.drop_index("ix_interview_questions_confidence", table_name="interview_questions")
    op.drop_index(op.f("ix_interview_questions_company_id"), table_name="interview_questions")
    op.drop_index(op.f("ix_interview_questions_category"), table_name="interview_questions")
    op.drop_table("interview_questions")
    op.drop_index(op.f("ix_interviews_status"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_scheduled_at"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_job_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_company_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_application_id"), table_name="interviews")
    op.drop_table("interviews")
    # ### end Alembic commands ###
