"""career ops integration

Revision ID: 26e04b74cce5
Revises: 6b57eeb0f8e5
Create Date: 2026-10-09 08:28:26.061851
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "26e04b74cce5"
down_revision: str | None = "6b57eeb0f8e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_ops_imports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_root", sa.String(length=1000), nullable=False),
        sa.Column("career_ops_version", sa.String(length=40), nullable=True),
        sa.Column("scan_triggered", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("scan_receipt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "file_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="RUNNING", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_career_ops_imports")),
    )
    op.add_column(
        "jobs", sa.Column("career_ops_score", sa.Numeric(precision=3, scale=1), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column("career_ops_evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("jobs", sa.Column("career_ops_report", sa.String(length=500), nullable=True))
    op.add_column("jobs", sa.Column("career_ops_status", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "career_ops_status")
    op.drop_column("jobs", "career_ops_report")
    op.drop_column("jobs", "career_ops_evaluation")
    op.drop_column("jobs", "career_ops_score")
    op.drop_table("career_ops_imports")
    # ### end Alembic commands ###
