"""offers

Revision ID: 1e7b2776c189
Revises: c69da179b5c1
Create Date: 2026-10-09 08:37:24.846852
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1e7b2776c189"
down_revision: str | None = "c69da179b5c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=True),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("variable_pay", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("bonus", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("equity", sa.String(length=300), nullable=True),
        sa.Column("equity_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_ctc", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("joining_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("work_model", sa.String(length=10), nullable=True),
        sa.Column("designation", sa.String(length=300), nullable=True),
        sa.Column(
            "benefits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("negotiation_notes", sa.Text(), nullable=True),
        sa.Column(
            "negotiation_log",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="RECEIVED", nullable=False),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("decision_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_offers_application_id_applications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_offers_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_offers_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
    )
    op.create_index(op.f("ix_offers_application_id"), "offers", ["application_id"], unique=False)
    op.create_index(op.f("ix_offers_company_id"), "offers", ["company_id"], unique=False)
    op.create_index(op.f("ix_offers_job_id"), "offers", ["job_id"], unique=False)
    op.create_index(op.f("ix_offers_status"), "offers", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_offers_status"), table_name="offers")
    op.drop_index(op.f("ix_offers_job_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_company_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_application_id"), table_name="offers")
    op.drop_table("offers")
    # ### end Alembic commands ###
