"""companies and contacts

Revision ID: ca4c4d80de77
Revises: 6f2c78259954
Create Date: 2026-10-08 23:28:50.429156
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ca4c4d80de77"
down_revision: str | None = "6f2c78259954"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_key", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=300), nullable=True),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("domain", sa.String(length=200), nullable=True),
        sa.Column("careers_url", sa.String(length=500), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("ats_provider", sa.String(length=40), nullable=True),
        sa.Column("ats_slug", sa.String(length=200), nullable=True),
        sa.Column("headquarters", sa.String(length=300), nullable=True),
        sa.Column("india_presence", sa.Boolean(), nullable=True),
        sa.Column(
            "india_locations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("company_type", sa.String(length=200), nullable=True),
        sa.Column("employee_range", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.String(length=10), nullable=True),
        sa.Column("tier", sa.String(length=10), nullable=True),
        sa.Column("hiring_status", sa.String(length=20), server_default="UNKNOWN", nullable=False),
        sa.Column(
            "job_search_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "verification_status", sa.String(length=30), server_default="DISCOVERED", nullable=False
        ),
        sa.Column("verification_override", sa.String(length=30), nullable=True),
        sa.Column("verification_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("name_key", name=op.f("uq_companies_name_key")),
    )
    op.create_index(op.f("ix_companies_domain"), "companies", ["domain"], unique=False)
    op.create_index(op.f("ix_companies_tier"), "companies", ["tier"], unique=False)
    op.create_index(
        op.f("ix_companies_verification_status"), "companies", ["verification_status"], unique=False
    )
    op.create_table(
        "company_field_sources",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("field", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("source_kind", sa.String(length=30), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_field_sources_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_field_sources")),
    )
    op.create_index(
        op.f("ix_company_field_sources_company_id"),
        "company_field_sources",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_company_field_sources_field",
        "company_field_sources",
        ["company_id", "field"],
        unique=False,
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("contact_type", sa.String(length=30), server_default="RECRUITER", nullable=False),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="NOT_CONTACTED", nullable=False),
        sa.Column("last_contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_followup_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_index(op.f("ix_contacts_status"), "contacts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contacts_status"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index("ix_company_field_sources_field", table_name="company_field_sources")
    op.drop_index(op.f("ix_company_field_sources_company_id"), table_name="company_field_sources")
    op.drop_table("company_field_sources")
    op.drop_index(op.f("ix_companies_verification_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_tier"), table_name="companies")
    op.drop_index(op.f("ix_companies_domain"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
